spring.application.name=retrofit
value.token=${DECOLECTA_TOKEN:}
spring.datasource.url=jdbc:postgresql://localhost:5432/retrofit_db
spring.datasource.username=postgres
spring.datasource.password=cero
spring.jpa.hibernate.ddl-auto=update
